// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFEEl0Lh7WBQWqzy4mhRznXQqakgYV858',
    appId: '1:246742686232:web:2e3b4454165007210f416d',
    messagingSenderId: '246742686232',
    projectId: 'fin-assist-ae064',
    authDomain: 'fin-assist-ae064.firebaseapp.com',
    storageBucket: 'fin-assist-ae064.firebasestorage.app',
    measurementId: 'G-B3MF869BR0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDM_JZX581BU53UL0XtaGDU-yegZ_6z4OM',
    appId: '1:246742686232:android:c2b882d8f350220b0f416d',
    messagingSenderId: '246742686232',
    projectId: 'fin-assist-ae064',
    storageBucket: 'fin-assist-ae064.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcA0MVrPzO-ikLlAzo2j7FGVrcpnTIlv8',
    appId: '1:246742686232:ios:8a2b8b574d2747660f416d',
    messagingSenderId: '246742686232',
    projectId: 'fin-assist-ae064',
    storageBucket: 'fin-assist-ae064.firebasestorage.app',
    iosBundleId: 'com.example.finAssist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcA0MVrPzO-ikLlAzo2j7FGVrcpnTIlv8',
    appId: '1:246742686232:ios:8a2b8b574d2747660f416d',
    messagingSenderId: '246742686232',
    projectId: 'fin-assist-ae064',
    storageBucket: 'fin-assist-ae064.firebasestorage.app',
    iosBundleId: 'com.example.finAssist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFEEl0Lh7WBQWqzy4mhRznXQqakgYV858',
    appId: '1:246742686232:web:cfb92220f63658e70f416d',
    messagingSenderId: '246742686232',
    projectId: 'fin-assist-ae064',
    authDomain: 'fin-assist-ae064.firebaseapp.com',
    storageBucket: 'fin-assist-ae064.firebasestorage.app',
    measurementId: 'G-9G9NHHHEHE',
  );
}
